// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iesvbngsjyhzfslpzfsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imllc3ZibmdzanloemZzbHB6ZnNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2Mjc3MzUsImV4cCI6MjA2ODIwMzczNX0.55d68lRDc3rt0zO0K0-zck7-7lI0hBX51el7FcfgiNk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});